const KEY='signal-capture-queue',URL_KEY='signal-workbench-url',TOKEN_KEY='signal-capture-token',status=document.querySelector('#status'),count=document.querySelector('#count'),list=document.querySelector('#list'),empty=document.querySelector('#empty');
const get=async()=>((await chrome.storage.local.get(KEY))[KEY]||[]);
const set=items=>chrome.storage.local.set({[KEY]:items});
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const tap=(button,text)=>{button.classList.remove('clicked');void button.offsetWidth;button.classList.add('clicked');if(text)status.textContent=text;};
function render(items){count.textContent=`${items.length} 条`;empty.hidden=!!items.length;list.innerHTML=items.slice().reverse().map(n=>`<article class="item"><div class="item-head"><h3>${esc(n.title||'无标题')}</h3><button class="delete-one" data-delete="${esc(n.note_id)}" title="删除这条">×</button></div><p>${esc(n.brand||'品牌待复核')} · ${esc(n.source_account||'未知作者')}</p><div class="meta"><span>点赞 ${esc(n.metrics?.likes?.raw||n.likes||'未读取')} · 评论 ${esc(n.metrics?.comments?.raw||'未读取')}</span><span class="${n.synced?'synced':''}">${n.synced?'已同步':'待同步'}</span></div><p>${esc(n.published_date||n.published_raw||'日期待复核')}</p></article>`).join('');}
async function currentTab(){const [tab]=await chrome.tabs.query({active:true,lastFocusedWindow:true});return tab;}
async function capture(){const button=document.querySelector('#capture');tap(button,'正在读取当前页…');try{const tab=await currentTab();if(!tab?.id)throw Error('没有找到当前标签页');await chrome.scripting.executeScript({target:{tabId:tab.id},files:['extractor-page.js']});const [{result}]=await chrome.scripting.executeScript({target:{tabId:tab.id},func:()=>window.__signalNote||null});if(!result)throw Error('请先打开一篇小红书笔记');const items=await get(),index=items.findIndex(n=>n.note_id===result.note_id);if(index>=0)items[index]={...items[index],...result};else items.push({...result,synced:false,queued_at:new Date().toISOString()});await set(items);status.textContent='已加入本地队列';render(items);}catch(error){status.textContent=error.message;}}
async function sync(){const button=document.querySelector('#sync');tap(button,'正在同步…');const items=await get(),pending=items.filter(n=>!n.synced);if(!pending.length){status.textContent='没有待同步内容';return;}try{const config=await chrome.storage.local.get([URL_KEY,TOKEN_KEY]),base=String(config[URL_KEY]||'http://127.0.0.1:4173').replace(/\/$/,'');const response=await fetch(`${base}/api/capture/batch`,{method:'POST',headers:{'Content-Type':'application/json','X-Signal-Collector':'1','X-Signal-Token':config[TOKEN_KEY]||''},body:JSON.stringify(pending)});const data=await response.json();if(!response.ok)throw Error(data.error||'同步失败');await set(items.map(n=>n.synced?n:{...n,synced:true}));status.textContent=`已同步 ${pending.length} 条到工作台`;render(await get());}catch(error){status.textContent=error.message;}}
async function removeOne(id,button){tap(button,'正在删除…');const items=await get();await set(items.filter(n=>n.note_id!==id));status.textContent='已删除这条笔记';}
async function clearAll(){const items=await get();if(!items.length){status.textContent='队列已经为空';return;}if(!confirm(`确定清空 ${items.length} 条本地笔记吗？`))return;tap(document.querySelector('#clear'),'正在清空…');await set([]);status.textContent='队列已清空';}
function csv(items){const columns=['note_id','brand','title','body','published_date','likes','likes_captured_at','source_account','source_type','url'],headers=['笔记 ID / note_id','品牌 / brand','标题 / title','正文 / body','发布日期 / published_date','点赞 / likes','点赞采集时间 / likes_captured_at','作者 / source_account','来源类型 / source_type','链接 / url'];const quote=v=>`"${String(v??'').replace(/"/g,'""')}"`;return '\uFEFF'+[headers.map(quote).join(','),...items.map(n=>columns.map(k=>quote(k==='likes'?n.metrics?.likes?.value??n.likes:n[k])).join(','))].join('\n');}
document.querySelector('#capture').onclick=capture;document.querySelector('#sync').onclick=sync;document.querySelector('#clear').onclick=clearAll;document.querySelector('#export').onclick=async()=>{const button=document.querySelector('#export');tap(button,'正在导出 CSV…');const blob=new Blob([csv(await get())],{type:'text/csv;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='signal-capture.csv';a.click();URL.revokeObjectURL(url);status.textContent='CSV 已导出';};
document.querySelector('#save-settings').onclick=async()=>{try{const input=document.querySelector('#workbench-url'),url=new URL(input.value.trim()||'http://127.0.0.1:4173');if(url.protocol!=='https:'&&url.hostname!=='127.0.0.1')throw Error('公网工作台必须使用 HTTPS');const base=url.origin;if(url.protocol==='https:'){const granted=await chrome.permissions.request({origins:[`${base}/*`]});if(!granted)throw Error('需要允许访问该工作台地址');}await chrome.storage.local.set({[URL_KEY]:base,[TOKEN_KEY]:document.querySelector('#capture-token').value.trim()});input.value=base;status.textContent='工作台连接已保存';}catch(error){status.textContent=error.message;}};
list.addEventListener('click',async e=>{const button=e.target.closest('[data-delete]');if(button)await removeOne(button.dataset.delete,button);});
chrome.storage.onChanged.addListener(change=>{if(change[KEY])render(change[KEY].newValue||[]);});get().then(render);
chrome.storage.local.get([URL_KEY,TOKEN_KEY]).then(config=>{document.querySelector('#workbench-url').value=config[URL_KEY]||'http://127.0.0.1:4173';document.querySelector('#capture-token').value=config[TOKEN_KEY]||'';});
