/* Throwaway functional demo. AI suggestions are deterministic rules, not model output. */
const MODULES = ['新品','联名','活动'];
function suggest(row) {
  const text = `${row.title} ${row.body || ''}`;
  const uncertain = /不确定|以门店为准|没有特别/.test(text);
  const rules = {新品:/新品|上新/,联名:/联名|IP/,活动:/买一赠一|套餐送|购买套餐送/};
  const declaredModules = String(row.modules || '').split(/[|｜]/).map(s => s.trim()).filter(m => MODULES.includes(m));
  const modules = declaredModules.length ? declaredModules : MODULES.filter(m => rules[m].test(text) && !(m==='新品' && /没有(?:特别的)?上新|并非新品|不是新品/.test(text)));
  const names = ['桂花乌龙','海獭日记','青提茉莉','买一赠一'];
  const name = names.find(n => text.includes(n));
  const action = String(row.action_name || '').trim() || name || row.title;
  return {...row, modules, action, peripherals: row.peripherals || (text.includes('玩偶') ? '玩偶' : ''),
    status:'pending', uncertain: uncertain || (!row.action_name && !name) || !modules.length,
    evidence: modules.map(m => `${m}：${text.match(rules[m])?.[0] ? `标题或正文命中“${text.match(rules[m])[0]}”` : '导入字段标注，需要人工核对。'}`).join('；') || '未找到明确市场动作，需要人工判断。', reason:'', history:[]};
}
function makeExportRows(notes) {
  const ids = new Map();
  return notes.filter(n => n.status==='approved').map(n => {
    const key=JSON.stringify([n.brand,n.action]); if(!ids.has(key)) ids.set(key,`ACTION-${String(ids.size+1).padStart(3,'0')}`);
    return {note_id:n.note_id,action_id:ids.get(key),brand:n.brand,action_name:n.action,title:n.title,published_date:n.published_date,likes:n.likes,likes_captured_at:n.likes_captured_at,modules:n.modules.join('|'),peripherals:n.peripherals,source_account:n.source_account,source_type:n.source_type,url:n.url||'',week_id:n.week_id||'',week_label:n.week_label||''};
  });
}
if(typeof module!=='undefined') module.exports={suggest,makeExportRows};
if(typeof document!=='undefined') {
const state={page:'overview',notes:[],captureInbox:[],weekFolders:[],activeFolderId:'',reviewFilter:'all',folderPage:0,suggested:false,selected:0,report:null,aiInsight:'',error:'',filter:'',search:'',file:'sample.csv',log:[]};
const $=s=>document.querySelector(s);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=n=>Number(n).toLocaleString('zh-CN');
const inScope=n=>!state.activeFolderId||n.week_id===state.activeFolderId;
const inReviewFilter=n=>state.reviewFilter==='confirmed'?n.status==='approved'&&n.locked:state.reviewFilter==='unconfirmed'?(n.status==='pending'||!n.locked):true;
const scopedNotes=()=>state.notes.filter(inScope);
const approved=()=>state.notes.filter(n=>inScope(n)&&n.status==='approved');
const pending=()=>state.notes.filter(n=>inScope(n)&&n.status==='pending');
const outstanding=()=>state.notes.filter(n=>inScope(n)&&(n.status==='pending'||((n.status==='approved'||n.status==='excluded')&&!n.locked)));
const badge=(s,c='')=>`<span class="tag ${c}">${esc(s)}</span>`;
const REVIEW_KEY='signal-review-v1';
const DEEPSEEK_KEY='signal-deepseek-key';
const SAMPLE_REV='sample-50-v1';
function readSnapshot(){try{return JSON.parse(localStorage.getItem(REVIEW_KEY)||'null');}catch{return null;}}
function saveSnapshot(){try{localStorage.setItem(REVIEW_KEY,JSON.stringify({file:state.file,sampleRevision:state.file==='sample.csv'?SAMPLE_REV:'',csv:state.sourceCsv,page:state.page,selected:state.selected,suggested:state.suggested,report:state.report,aiInsight:state.aiInsight,log:state.log,notes:state.notes,captureInbox:state.captureInbox,weekFolders:state.weekFolders,activeFolderId:state.activeFolderId,reviewFilter:state.reviewFilter,folderPage:state.folderPage}));}catch{toast('浏览器存储空间不足，当前页面关闭后可能需要重新复核。');}}
function clearSnapshot(){try{localStorage.removeItem(REVIEW_KEY);state.captureInbox=[];state.weekFolders=[];state.activeFolderId='';}catch{}}
function restoreSnapshot(rows,file,csv){const saved=readSnapshot();if(!saved||saved.file!==file||saved.csv!==csv||(file==='sample.csv'&&saved.sampleRevision!==SAMPLE_REV)||!Array.isArray(saved.notes))return false;const byId=new Map(saved.notes.map(n=>[n.note_id,n]));if(rows.some(n=>!byId.has(n.note_id)))return false;state.notes=rows.map(n=>({...n,...byId.get(n.note_id)}));state.page=['overview','review','report','method','collection'].includes(saved.page)?saved.page:'overview';state.selected=Math.min(Number(saved.selected)||0,Math.max(rows.length-1,0));state.suggested=!!saved.suggested;state.report=saved.report||null;state.aiInsight=saved.aiInsight||'';state.log=Array.isArray(saved.log)?saved.log:[];state.captureInbox=Array.isArray(saved.captureInbox)?saved.captureInbox:[];state.weekFolders=Array.isArray(saved.weekFolders)?saved.weekFolders:[];state.activeFolderId=saved.activeFolderId||'';state.reviewFilter=saved.reviewFilter||'all';state.folderPage=Math.max(Number(saved.folderPage)||0,0);return true;}
function toast(message){$('#toast').textContent=message;$('#toast').style.display='block';clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').style.display='none',3500);}
function heading(kicker,title,sub,actions=''){return `<div class="page-heading"><div><p class="eyebrow">${kicker}</p><h1>${title}</h1><p class="sub">${sub}</p></div><div class="actions">${actions}</div></div>`;}
function stats(){const ns=state.notes;const groups=new Set(ns.filter(n=>n.action).map(n=>JSON.stringify([n.brand,n.action])));return `<div class="stats">${[
  ['观察内容',ns.length,'篇帖子，保留采集时间','▤'],['动作候选',state.suggested?groups.size:'—',state.suggested?'按品牌与动作名称归并':'运行分析后生成','◈'],['待复核',state.suggested?outstanding().length:'—',state.suggested?`${ns.filter(n=>n.uncertain&&(!n.locked||n.status==='pending')).length} 篇需要特别关注`:'等待分类建议','◎'],['已确认',approved().length,`<em>${ns.length?Math.round(approved().length/ns.length*100):0}%</em> 内容已确认`,'✓']
].map(([label,num,note,icon])=>`<div class="stat"><div class="stat-head">${label}<i>${icon}</i></div><strong>${num}</strong><small>${note}</small></div>`).join('')}</div>`;}
function overview(){const done=state.suggested;return heading('SIGNAL / WORKSPACE','让行业线索，成为下一步行动。','从一批帖子，到一份有据可查的饮品行业观察。',`<button class="secondary" data-go="review">导入数据</button><button class="primary" data-go="${state.report?'report':'review'}">${state.report?'查看报告 ↗':'进入复核台 ↗'}</button>`)+
`<section class="hero"><div><p class="eyebrow">YOUR NEXT STEP</p><h2>${state.report?'报告已就绪，回到证据检查每一个判断。':done?'判断交给你，重复整理交给工作流。':'先让五十条线索，找到它们之间的联系。'}</h2><p>${done?`还有 ${outstanding().length} 篇待处理。每一条确认，都会影响最终的统计与报告。`:`已载入 ${state.notes.length} 篇模拟帖子，覆盖多个真实茶饮品牌与公开活动模式。运行规则演示，体验 AI 辅助分析与人工复核流程。`}</p><button class="primary" ${done?'data-go="review"':'data-run'}>${done?'继续复核 →':'生成分析建议 →'}</button></div><div class="hero-art" aria-hidden="true"><div class="orbit"><span>◈</span><small>signal found ↗</small></div></div></section>`+stats()+
`<div class="columns"><section class="panel"><div class="panel-heading"><h2>本次观察进度</h2>${badge('四步完成交付','gray')}</div>${[
['01','整理观察样本',`${state.notes.length} 篇内容 · ${new Set(state.notes.map(n=>n.brand)).size} 个品牌 · ${esc(state.file)}`,'已载入'],
['02','生成标签与动作候选','关键词规则模拟 AI · 保留建议依据',done?'已生成':'待开始'],
['03','人工复核与修正',`${approved().length} 篇已确认 · ${state.notes.filter(n=>n.status==='excluded').length} 篇已排除`,done?'进行中':'等待建议'],
['04','生成可追溯报告','统计只基于已确认内容，发布前处理全部待复核项',state.report?'已完成':'待生成']
].map(([n,title,sub,status])=>`<div class="step"><div class="step-number">${n}</div><div class="step-info"><h3>${title}</h3><p>${sub}</p></div>${badge(status,status==='已完成'||status==='已载入'?'green':'gray')}</div>`).join('')}</section>
<section class="panel"><div class="panel-heading"><h2>观察提示</h2>${badge('方法先行')}</div><div class="insight"><span class="label">01 / EVIDENCE</span><p><strong>先确认发生了什么，再讨论热度。</strong></p><p>同一动作可能由多个账号发布，先归并，再计算表现。</p></div><div class="insight"><span class="label">02 / HUMAN IN THE LOOP</span><p><strong>模糊描述留给人判断。</strong></p><p>“不确定是不是联名”的帖子不应被自动当作确认事实。</p></div><div class="insight"><span class="label">03 / MEASUREMENT</span><p><strong>热度不等于销量。</strong></p><p>点赞是当前样本的内容反馈；这版没有历史周期，不展示环比。</p></div></section></div>
<section class="panel"><div class="panel-heading"><h2>观察样本</h2><button class="text-button" data-go="review">查看全部 →</button></div><div class="table-wrap"><table><thead><tr><th>内容 / 品牌</th><th>来源账号</th><th>点赞</th><th>复核状态</th></tr></thead><tbody>${state.notes.slice(0,5).map(n=>`<tr><td><strong>${esc(n.title)}</strong><small>${esc(n.brand)}</small></td><td>${esc(n.source_account)}</td><td>${fmt(n.likes)}</td><td>${statusTag(n)}</td></tr>`).join('')}</tbody></table></div></section>`;}
function statusTag(n){return !n.locked&&n.status!=='pending'?badge('未确认','amber'):n.status==='approved'?badge('已确认','green'):n.status==='excluded'?badge('已排除','gray'):badge(state.suggested?'待复核':'待分析','amber');}
function lockControl(n){return n.status==='pending'?'':`<button type="button" class="lock-control ${n.locked?'locked':'unlocked'}" data-toggle-lock>${n.locked?'已锁定':'未锁定'}</button>`;}
function review(){const n=inScope(state.notes[state.selected])?state.notes[state.selected]:null;return heading('SIGNAL / REVIEW','在发布之前，多问一句为什么。','逐条核对建议与原文。当前集合：'+(currentFolderLabel()||'未指定')+'。确认同名动作即可归并；修改动作名即可拆分。',`<button class="secondary" data-run ${state.suggested?'disabled':''}>生成建议</button><button class="secondary" data-bulk-confirm ${!state.suggested?'disabled':''}>一键确认当前集合</button><button class="primary" data-publish ${!state.suggested||outstanding().length||!approved().length?'disabled':''}>生成报告 ↗</button>`)+
collectionPicker()+
`<div class="upload-box"><strong>导入观察样本</strong><p class="muted">CSV UTF-8 · 最大 10 MB · 导入成功后替换本次工作区 · <a href="/sample.csv" download>下载示例模板</a></p><input id="upload" aria-label="上传 CSV 数据" type="file" accept=".csv">${state.error?`<div role="alert" class="error">${esc(state.error)}</div>`:''}</div>`+
`<div class="panel-heading"><p class="count-label">${scopedNotes().length} 篇内容 · ${approved().length} 已确认 · ${outstanding().length} 待复核</p>${badge('规则模拟 AI · 非真实模型输出','amber')}</div><div class="review-filter"><button class="text-button" data-review-filter="unconfirmed">未确认</button><button class="text-button" data-review-filter="confirmed">已确认</button><button class="text-button" data-review-filter="all">所有</button></div><div class="review-layout"><div class="queue">${state.notes.map((n,i)=>({n,i})).filter(({n})=>inScope(n)&&inReviewFilter(n)).map(({n,i})=>`<button class="queue-item ${i===state.selected?'selected':''}" data-select="${i}">${statusTag(n)}<strong>${esc(n.title)}</strong><small>${esc(n.brand)} · ${fmt(n.likes)} 赞 ${n.uncertain?'· 需关注':''}</small></button>`).join('')}</div><section class="panel review-panel">${n?reviewNote(n):'<p>没有内容。</p>'}</section></div>`;}
function reviewNote(n){const locked=!!n.locked;const disabled=locked?'disabled':'';return `<div class="panel-heading"><span class="muted">${esc(n.note_id)} · ${esc(n.source_account)} · ${esc(n.published_date)}</span>${statusTag(n)}</div><h2>${esc(n.title)}</h2><blockquote>${esc(n.body || n.title)}</blockquote>${state.suggested?`${badge(n.uncertain?'证据不充分 · 请重点核对':'已找到文本依据',n.uncertain?'amber':'green')}<p class="muted">${esc(n.evidence)}</p><form id="review-form"><div class="fields"><label>品牌<input name="brand" value="${esc(n.brand)}" required maxlength="80" ${disabled}></label><label>归并后的动作名称<input name="action" value="${esc(n.action)}" required maxlength="150" ${disabled}></label><fieldset class="wide"><legend>观察模块（可多选）</legend><div class="checks">${MODULES.map(m=>`<label><input type="checkbox" name="modules" value="${m}" ${n.modules.includes(m)?'checked':''} ${disabled}>${m}</label>`).join('')}</div></fieldset><label>周边标签（用 | 分隔）<input name="peripherals" value="${esc(n.peripherals)}" maxlength="150" ${disabled}></label><label>复核说明${n.uncertain?'（此条必填）':''}<input name="reason" placeholder="例如：正文不构成明确活动，排除" value="${esc(n.reason)}" maxlength="300" ${n.uncertain?'required':''} ${disabled}></label></div><div class="review-toolbar">${lockControl(n)}<button type="button" class="secondary" data-exclude ${disabled}>排除这篇内容</button><button class="primary" type="submit" ${disabled}>确认并看下一条 →</button></div></form><p class="audit">${n.history.length?n.history.map(h=>`${esc(h.time)} · ${esc(h.text)}`).join('<br>'):'尚无人工操作记录。修改已确认内容后，旧报告将失效。'}</p>`:`<div class="empty"><h3>先生成标签建议</h3><p>点击上方“生成建议”，再开始复核。</p></div>`}`;}
const reportPct=(part,total)=>total?(part/total*100).toFixed(1):'0.0';
const reportPeriod=notes=>{const dates=notes.map(n=>n.publishedDate).filter(Boolean).sort();return dates.length?`${dates[0]} — ${dates.at(-1)}`:'日期未记录';};
const moduleActions=(r,module)=>r.brandActions.filter(a=>a.modules.includes(module));
function moduleChapter(r,module,index){
  const summary=r.summary.moduleSummary[module],items=moduleActions(r,module),top=items[0],tone={新品:'fresh',联名:'collab',活动:'campaign'}[module];
  if(!top)return `<section id="module-${index}" class="report-chapter ${tone}"><p class="chapter-index">0${index} · ${module}观察</p><h2>本期没有已确认的${module}动作</h2><p>继续补充样本后，这里会生成排行与结构判断。</p></section>`;
  const counts=new Map();items.flatMap(a=>a.collaboration.peripherals).forEach(tag=>counts.set(tag,(counts.get(tag)||0)+1));
  const tags=[...counts].sort((a,b)=>b[1]-a[1]||a[0].localeCompare(b[0],'zh-CN')).slice(0,12);
  const buckets={新品:[['品类与原料',/茶|果|奶|芒|桂|青提|鲜橙|山楂|抹茶|咖啡|冰饮|鲜果|玉露/],['陈列与触点',/.*/]],联名:[['联名载体',/联名|杯|纸|玩偶|周边|贴纸|文创|主题店/],['互动方式',/.*/]],活动:[['互动玩法',/打卡|抽奖|买一赠一|买赠|会员|一元喝|优惠|小程序|校园/],['触点与物料',/.*/]]}[module];
  const section=(title,matcher)=>{const values=tags.filter(([tag])=>matcher instanceof RegExp?matcher.test(tag):matcher(tag));return values.length?`<div class="aside-section"><p>${title}</p><div class="aside-chips">${values.map(([tag,count])=>`<span class="aside-chip">${esc(tag)} <b>${count}</b></span>`).join('')}</div></div>`:'';};
  const share=reportPct(top.metrics.likes,summary.likes),brands=new Set(items.map(a=>a.primaryBrand)).size;
  return `<section id="module-${index}" class="report-chapter ${tone}"><div class="chapter-heading"><p class="chapter-index">0${index} · ${module}观察</p><h2>${module==='新品'?`${esc(top.primaryBrand)}「${esc(top.name)}」领跑新品关注` : module==='联名'?`${esc(top.name)}成为本期最受关注的联名动作`:`${esc(top.name)}贡献本期最高活动热度`}</h2></div><div class="chapter-finding"><strong>${summary.noteCount} 篇内容形成 ${items.length} 个动作，累计 ${fmt(summary.likes)} 赞。</strong><p>第一名占本模块点赞的 ${share}%；本期有 ${summary.viralNoteCount} 篇内容达到千赞。</p></div><div class="chapter-grid"><section class="chapter-ranking"><div class="panel-heading"><h3>${module}动作排行</h3><span class="muted">点击查看原始证据</span></div>${items.slice(0,6).map((a,i)=>`<div class="rank-row"><span>${String(i+1).padStart(2,'0')}</span><button class="text-button" data-detail="${a.id}">${esc(a.primaryBrand)} · ${esc(a.name)}</button><div class="rank-track"><span style="width:${a.metrics.likes/top.metrics.likes*100}%"></span></div><strong>${fmt(a.metrics.likes)}</strong></div>`).join('')}</section><aside class="chapter-aside"><p>结构观察</p><h3>${brands} 个品牌参与，平均每篇 ${fmt(Math.round(summary.averageLikes))} 赞</h3><dl><div><dt>动作数量</dt><dd>${items.length}</dd></div><div><dt>千赞内容</dt><dd>${summary.viralNoteCount}</dd></div><div><dt>头部占比</dt><dd>${share}%</dd></div></dl>${section(buckets[0][0],buckets[0][1])}${section(buckets[1][0],tag=>!buckets[0][1].test(tag))}<p class="aside-foot">标签统计来自已确认样本，数字代表提及该标签的动作数。</p></aside></div></section>`;
}
function deepSeekPanel(){const configured=!!sessionStorage.getItem(DEEPSEEK_KEY);return `<section class="panel ai-panel"><div class="panel-heading"><div><p class="section-kicker">DEEPSEEK ANALYSIS</p><h2>让模型补充商业判断</h2></div>${badge('固定提示词','gray')}</div><p class="muted">仅发送当前集合的已确认数据。模型固定为 deepseek-flash，分析结果不会修改原始数据。</p><div class="ai-controls"><label>DeepSeek API Key<input id="deepseek-key" type="password" autocomplete="off" placeholder="${configured?'已保存于当前会话，可直接重新分析':'sk-...'}"></label><button class="primary" type="button" data-ai-analyze>${state.aiInsight?'重新生成分析':'生成 AI 分析'}</button></div><small class="muted">Key 仅保存在当前浏览器会话，不写入项目、复核记录或导出文件。</small>${state.aiInsight?`<article class="ai-result"><div class="ai-result-head"><strong>DeepSeek 分析结果</strong><span>基于已复核样本</span></div><div>${esc(state.aiInsight)}</div></article>`:'<div class="ai-empty">填写 API Key 后，生成核心判断、机会方向、风险限制和下一步动作。</div>'}</section>`;}
function report(){if(!state.report)return heading('SIGNAL / REPORT','一份报告，从可信的样本开始。','先完成复核，再让统计和结论一起形成。')+`<section class="empty"><p class="eyebrow">READY WHEN YOU ARE</p><h2>报告等待生成</h2><p>${state.suggested?`还有 ${outstanding().length} 篇待复核，${approved().length} 篇已确认。`:'请先生成建议并确认内容。'}</p><button class="primary" data-go="review">前往复核台 →</button></section>`;
const r=state.report,sum=r.summary,top=r.brandActions[0],folder=r.notes.find(n=>n.weekLabel)?.weekLabel||currentFolderLabel(),actions=r.brandActions.filter(a=>(!state.filter||a.modules.includes(state.filter))&&`${a.name} ${a.primaryBrand}`.toLowerCase().includes(state.search.toLowerCase())),sources=new Set(r.notes.map(n=>n.source.accountName).filter(Boolean)).size,brands=new Set(r.notes.map(n=>n.brand)).size,strongest=MODULES.map(m=>[m,sum.moduleSummary[m]]).sort((a,b)=>b[1].likes-a[1].likes)[0],topFiveShare=reportPct(r.brandActions.slice(0,5).reduce((n,a)=>n+a.metrics.likes,0),sum.likes),topSummary=r.brandActions.length>5?`前五名集中 ${topFiveShare}% 点赞`:`${r.brandActions.length} 个已确认动作的热度分布`,insights=[`${top.primaryBrand}「${top.name}」以 ${fmt(top.metrics.likes)} 赞领跑，占本期点赞 ${reportPct(top.metrics.likes,sum.likes)}%。`,`${strongest[0]}是本期热度最高的观察模块，累计 ${fmt(strongest[1].likes)} 赞。`,`${sum.viralNoteCount} 篇内容达到千赞，占已确认内容 ${reportPct(sum.viralNoteCount,sum.noteCount)}%。`,`${sum.noteCount} 篇样本来自 ${sources} 个账号，适合判断内容信号，不代表销量或全平台份额。`];return heading('SIGNAL / REPORT','饮品行业观察',`${folder?`集合：${esc(folder)} · `:''}${reportPeriod(r.notes)} · 已复核快照`,`<button class="secondary" data-export="csv">导出明细 ↓</button><button class="primary" data-export="docx">下载 Word 报告 ↓</button>`)+
`<section class="report-intro"><div class="report-intro-title"><p>本期执行摘要</p><h2>从 ${sum.noteCount} 篇内容中，找到值得继续追踪的品牌动作。</h2><div class="report-scope"><span>${brands} 个品牌</span><span>${sources} 个账号</span><span>${r.brandActions.length} 个动作</span><span>${fmt(sum.likes)} 累计赞</span></div></div><div class="report-findings">${insights.map((text,i)=>`<article><b>${String(i+1).padStart(2,'0')}</b><p>${esc(text)}</p></article>`).join('')}</div></section>
${deepSeekPanel()}
<section class="module-overview">${MODULES.map((m,i)=>{const summary=sum.moduleSummary[m],lead=moduleActions(r,m)[0];return `<a class="module-card ${['fresh','collab','campaign'][i]}" href="#module-${i+1}"><span>${m}</span><h3>${lead?esc(lead.name):'暂无已确认动作'}</h3><strong>${fmt(summary.likes)} <small>赞</small></strong><p>${summary.noteCount} 篇内容 · ${summary.viralNoteCount} 篇千赞</p><i>查看${m}观察 ↓</i></a>`;}).join('')}</section>
<section class="report-top"><div class="report-top-heading"><div><p>本期最受关注的品牌动作</p><h2>${topSummary}</h2></div><span>${r.brandActions.length} 个动作 · ${fmt(sum.likes)} 赞</span></div>${r.brandActions.slice(0,5).map((a,i)=>`<div class="rank-row"><span>${String(i+1).padStart(2,'0')}</span><button class="text-button" data-detail="${a.id}">${esc(a.primaryBrand)} · ${esc(a.name)}</button><div class="rank-track"><span style="width:${a.metrics.likes/top.metrics.likes*100}%"></span></div><strong>${fmt(a.metrics.likes)}</strong></div>`).join('')}</section>
${MODULES.map((m,i)=>moduleChapter(r,m,i+1)).join('')}
<section class="report-decisions"><div><p>下一步建议</p><h2>把结论变成下一轮观察任务</h2></div><article><span>优先跟进</span><h3>${esc(top.primaryBrand)}「${esc(top.name)}」</h3><p>当前样本热度最高，下一轮补充品牌官方与达人内容，确认热度是否持续。</p></article><article><span>继续观察</span><h3>${strongest[0]}模块</h3><p>本期累计 ${fmt(strongest[1].likes)} 赞，建议比较下一集合的内容数量与千赞率。</p></article><article><span>补充证据</span><h3>${sum.noteCount<20?'扩大样本后再判断':'保持相同口径复采'}</h3><p>当前结论仅描述已确认样本，不外推销量、市场份额或全平台趋势。</p></article></section>
<section class="panel action-library"><div class="panel-heading"><div><p class="section-kicker">证据库</p><h2>找到你关心的品牌动作</h2></div><span class="muted">点击动作，回到原始内容</span></div><div class="filterbar"><input id="search" aria-label="搜索品牌或动作" placeholder="搜索品牌、动作名称…" value="${esc(state.search)}"><select id="module-filter" aria-label="筛选模块"><option value="">全部模块</option>${MODULES.map(m=>`<option ${state.filter===m?'selected':''}>${m}</option>`).join('')}</select></div><div class="table-wrap"><table><thead><tr><th>品牌动作</th><th>观察模块</th><th>内容数</th><th>累计点赞</th><th></th></tr></thead><tbody>${actions.map(a=>`<tr><td><strong>${esc(a.name)}</strong><small>${esc(a.primaryBrand)}</small></td><td>${a.modules.map(m=>badge(m)).join(' ')}</td><td>${a.metrics.noteCount}</td><td>${fmt(a.metrics.likes)}</td><td><button class="text-button" data-detail="${a.id}">查看证据 ↗</button></td></tr>`).join('')||'<tr><td colspan="5">没有匹配的动作，试试其他关键词。</td></tr>'}</tbody></table></div></section><p class="report-note">数据说明：${r.notes.length} 篇纳入 · ${scopedNotes().filter(n=>n.status==='excluded').length} 篇排除 · 点赞 ≥ 1,000 为千赞内容 · 模块可重叠，不可直接相加。</p>`;}
function method(){return heading('SIGNAL / METHODOLOGY','看得见结果，也看得见依据。','这份 demo 展示业务闭环；数据与自动分析的边界在这里说明。')+`<div class="method-grid"><section class="panel"><p class="eyebrow">01 / SOURCE</p><h2>数据来源与范围</h2><ul><li>默认十篇自编帖子，品牌、作者与案例均为虚构。</li><li>支持模板格式 CSV；数据仅在本机处理。</li><li>点赞保留采集截点；没有历史周，无法判断增长。</li><li>复核状态保存在当前浏览器；点击“重置演示”才会清除。</li></ul></section><section class="panel"><p class="eyebrow">02 / INTELLIGENCE</p><h2>AI 能力演示的边界</h2><ul><li>分类与动作建议使用关键词规则；报告页可选调用 DeepSeek 生成解释性分析。</li><li>DeepSeek 只接收当前集合的已确认数据，不会修改原始记录。</li><li>不确定表达进入重点复核，所有帖子需要人确认或排除。</li><li>模型结论必须结合样本范围审阅，不能凭模型自报置信度验收。</li></ul></section><section class="panel"><p class="eyebrow">03 / METRICS</p><h2>统计如何计算</h2><ul><li>同品牌、同动作名称归并；不同名称形成不同动作。</li><li>点赞按帖子 ID 去重后求和，千赞阈值为 1,000。</li><li>同一帖子可属于多个模块，总体统计只计一次。</li><li>主分类默认联名 → 新品 → 活动；本版没有人工覆盖主分类。</li></ul></section><section class="panel"><p class="eyebrow">04 / EVALUATION</p><h2>未来如何证明提效</h2><ul><li>在同一批数据上比较人工流程和辅助流程的完成时间。</li><li>检查标签准确率、动作归并错误和报告返工。</li><li>记录模型成本、失败重试和人均复核耗时。</li><li>当前未测量，不展示虚构的节省工时或商业收益。</li></ul></section></div><section class="panel"><h2>本次操作记录</h2><p class="audit">${state.log.length?state.log.map(esc).join('<br>'):'暂无操作。去复核台开始体验。'}</p></section>`;}
function currentFolderLabel(){return state.weekFolders.find(f=>f.id===state.activeFolderId)?.label||'';}
function makeFolder(dateValue,name){const d=new Date((dateValue||new Date().toISOString().slice(0,10))+'T00:00:00'),day=d.getDay()||7;d.setDate(d.getDate()-day+1);const start=d.toISOString().slice(0,10),endDate=new Date(d);endDate.setDate(d.getDate()+6);const end=endDate.toISOString().slice(0,10),label=String(name||'').trim()||start.replaceAll('-','.')+' – '+end.replaceAll('-','.');return{id:String(name||'').trim()?'folder-'+Date.now():'week-'+start,label,start,end};}
function createFolder(dateValue,name){const folder=makeFolder(dateValue,name);state.weekFolders=[...state.weekFolders.filter(f=>f.id!==folder.id),folder];state.activeFolderId=folder.id;state.report=null;saveSnapshot();render();toast('已创建集合：'+folder.label);}
function renameFolder(name){const value=String(name||'').trim(),folder=state.weekFolders.find(f=>f.id===state.activeFolderId);if(!folder||!value)return toast('请选择集合并输入新名称。');if(folder.id==='sample-data')return toast('模拟数据集合名称固定。');folder.label=value;state.notes.forEach(n=>{if(n.week_id===folder.id)n.week_label=value;});state.report=null;saveSnapshot();render();toast('集合已重命名。');}
function folderManager(){const options=state.weekFolders.map(f=>'<option value="'+esc(f.id)+'" '+(f.id===state.activeFolderId?'selected':'')+'>'+esc(f.label)+'</option>').join('');return '<section class="panel folder-manager"><div class="panel-heading"><div><p class="eyebrow">COLLECTIONS</p><h2>当前工作集合</h2></div><span class="muted">'+(currentFolderLabel()||'未选择')+'</span></div><p class="muted">集合是工作台里的大容器；笔记、报告和复核状态都归属于当前集合。</p><div class="folder-manager-grid"><label>选择集合<select id="folder-dashboard-select"><option value="">请选择集合</option>'+options+'</select></label><label>新集合名称<input id="folder-name" placeholder="例如：9.21 联名观察"></label><label>起始日期<input id="folder-date" type="date" value="'+new Date().toISOString().slice(0,10)+'"></label><button class="secondary" type="button" data-folder-action="create">创建集合</button><label>重命名当前集合<input id="folder-rename" value="'+esc(currentFolderLabel())+'" placeholder="选择后输入新名称"></label><button class="secondary" type="button" data-folder-action="rename" '+(state.activeFolderId&&state.activeFolderId!=='sample-data'?'':'disabled')+'>保存名称</button></div></section>';}
function collectionPicker(){const options=state.weekFolders.map(f=>{const count=state.notes.filter(n=>n.week_id===f.id).length;return '<option value="'+esc(f.id)+'" '+(f.id===state.activeFolderId?'selected':'')+'>'+esc(f.label)+' · '+count+' 篇笔记</option>';}).join('');return '<section class="collection-picker"><div><p class="eyebrow">CURRENT COLLECTION</p><strong>'+(currentFolderLabel()||'请选择集合')+'</strong><p class="muted">选择一个集合后，左侧列表、复核进度和报告都会只显示它的笔记子集。</p></div><label>切换集合<select id="folder-review-select"><option value="">请选择集合</option>'+options+'</select></label></section>';}
const {collection,mountCollector}=window.SignalCollector({state,$,esc,heading,suggest,saveSnapshot,go,toast,createFolder,renameFolder});
function render(){ const queueTop=document.querySelector('.queue') && document.querySelector('.queue').scrollTop; $('#main').innerHTML=({overview,review,report,method,collection}[state.page])(); if(state.page==='overview')$('#main').insertAdjacentHTML('beforeend',folderManager());document.querySelectorAll('[data-review-filter]').forEach(b=>b.classList.toggle('active',b.dataset.reviewFilter===state.reviewFilter));document.querySelectorAll('[data-page]').forEach(b=>b.classList.toggle('active',b.dataset.page===state.page));$('#pending-badge').textContent=state.suggested?outstanding().length:state.notes.length;if(state.page==='collection')mountCollector();const queue=document.querySelector('.queue');if(queueTop!=null&&queue)queue.scrollTop=queueTop;}
function go(page){state.page=page;saveSnapshot();render();window.scrollTo({top:0,behavior:'instant'});}
async function loadCSV(csv,file){
 const p=Papa.parse(csv.replace(/^\uFEFF/,''),{header:true,skipEmptyLines:'greedy',transformHeader:s=>s.trim()});
 if(p.errors.length)throw Error('CSV 格式错误：'+p.errors[0].message);
 const required=['note_id','brand','title','published_date','likes','likes_captured_at'];
 if(required.some(k=>!p.meta.fields?.includes(k)))throw Error('缺少必需列：'+required.filter(k=>!p.meta.fields?.includes(k)).join('、'));
 if(!p.data.length)throw Error('文件里没有帖子。');
 // Reuse the existing validator before replacing the active workspace. No imported suggestions are treated as approvals.
 const rows=p.data.map((n,i)=>({...n,action_id:`validate-${i}`,action_name:n.title,modules:'新品'}));
 const response=await fetch('/api/report',{method:'POST',body:Papa.unparse(rows)});const validation=await response.json();if(!response.ok)throw Error(validation.error);
 state.sourceCsv=csv;state.file=file;state.selected=0;state.error='';
 if(!restoreSnapshot(p.data,file,csv)){state.notes=p.data.map(n=>({...n,status:'pending',history:[],reason:'',locked:false}));state.suggested=false;state.report=null;state.log=[`${new Date().toLocaleTimeString()} · 载入 ${p.data.length} 篇内容（${file}）`];}
 const demoIds=new Set(Array.from({length:50},(_,i)=>`N${String(i+1).padStart(3,'0')}`)),demoNotes=state.notes.filter(n=>demoIds.has(n.note_id));
 // ponytail: the bundled fixture IDs migrate old snapshots; arbitrary imports should provide their own collection metadata.
 if(demoNotes.length===50){let demo=state.weekFolders.find(f=>f.id==='sample-data');if(!demo){demo={id:'sample-data',label:'模拟数据',start:'',end:''};state.weekFolders=[demo,...state.weekFolders.filter(f=>f.id!==demo.id)];}demo.label='模拟数据';state.notes=state.notes.map(n=>demoIds.has(n.note_id)?{...n,week_id:demo.id,week_label:demo.label}:n);if(!state.activeFolderId)state.activeFolderId=demo.id;}
 if(file==='sample.csv'&&!state.weekFolders.length){const folder={id:'sample-data',label:'模拟数据',start:'',end:''};state.weekFolders=[folder];state.activeFolderId=folder.id;state.notes=state.notes.map(n=>({...n,week_id:folder.id,week_label:folder.label}));}
 if(file==='sample.csv'){const demo=state.weekFolders.find(f=>f.id==='sample-data');if(demo){demo.label='模拟数据';state.notes=state.notes.map(n=>n.week_id===demo.id?{...n,week_label:demo.label}:n);if(!state.activeFolderId)state.activeFolderId=demo.id;}}
 saveSnapshot();
}
function run(){if(state.suggested)return;state.notes=state.notes.map(suggest);state.suggested=true;state.report=null;state.log.push(`${new Date().toLocaleTimeString()} · 生成规则建议（非模型输出）`);saveSnapshot();render();toast('建议已生成。请逐条核对后生成报告。');}
function confirmAll(){
 const candidates=state.notes.filter(n=>inScope(n)&&!n.locked&&n.status==='pending');
 if(!state.suggested)return toast('请先生成建议，再一键确认。');
 if(!candidates.length)return toast('当前集合没有待确认内容。');
 const time=new Date().toLocaleTimeString();
 candidates.forEach(n=>{n.status='approved';n.locked=true;n.reason=n.reason||'一键确认当前集合（演示）';n.history.push({time,text:`确认；原建议：${n.brand} / ${n.action} / ${n.modules.join('、')}；${n.reason}`});state.log.push(`${n.note_id} · 一键确认当前集合`);});
 state.report=null;state.selected=state.notes.indexOf(candidates[0]);saveSnapshot();render();toast(`已确认并锁定 ${candidates.length} 篇内容。`);
}
function saveReview(exclude=false){const n=state.notes[state.selected],form=$('#review-form');if(!form)return;if(n.locked)return toast('这条内容已锁定，请先点击“已锁定”解锁后再修改。');const fd=new FormData(form);const reason=String(fd.get('reason')||'').trim();const modules=fd.getAll('modules');
 if(!exclude&&(!String(fd.get('brand')).trim()||!String(fd.get('action')).trim()||!modules.length))return toast('请填写品牌、动作名称，并选择至少一个模块。');
 if((exclude||n.uncertain)&&!reason)return toast('请补充复核说明，记录确认或排除的依据。');
 const before=`${n.brand} / ${n.action} / ${n.modules.join('、')}`;
 n.brand=String(fd.get('brand')).trim();n.action=String(fd.get('action')).trim();n.modules=modules;n.peripherals=String(fd.get('peripherals')).trim();n.reason=reason;n.status=exclude?'excluded':'approved';n.locked=true;
 const text=`${exclude?'排除':'确认'}；原建议：${before}；复核后：${n.brand} / ${n.action} / ${modules.join('、')}；${reason||'核对无误'}`;
 n.history.push({time:new Date().toLocaleTimeString(),text});state.log.push(`${n.note_id} · ${text}`);state.report=null;const current=state.selected;let next=state.notes.findIndex((item,i)=>i>current&&!item.locked);if(next<0)next=state.notes.findIndex(item=>!item.locked);if(next>=0)state.selected=next;saveSnapshot();render();toast(outstanding().length?'已保存，进入下一篇。':'全部处理完成，可以生成报告了。');
}
function toggleLock(){const n=state.notes[state.selected];if(!n||n.status==='pending')return;n.locked=!n.locked;if(!n.locked)state.report=null;state.log.push(`${n.note_id} · ${n.locked?'锁定复核结果':'解锁复核结果，可重新修改'}`);saveSnapshot();render();toast(n.locked?'已锁定，避免误触修改。':'已解锁，现在可以修改复核结果。');}
async function publish(){if(!state.suggested||outstanding().length||!approved().length)return toast('请先处理当前集合内的全部帖子，并锁定所有复核结果。');const response=await fetch('/api/report',{method:'POST',body:Papa.unparse(makeExportRows(scopedNotes()))});const data=await response.json();if(!response.ok)throw Error(data.error);state.report=data;state.aiInsight='';state.log.push(`${new Date().toLocaleTimeString()} · 生成报告：${data.notes.length} 篇内容，${data.brandActions.length} 个动作`);saveSnapshot();go('report');toast('报告已生成，所有数字均来自当前集合的已确认内容。');}
function detail(id){const a=state.report.brandActions.find(a=>a.id===id);if(!a)return;$('#detail-content').innerHTML=`<p class="eyebrow">ACTION / EVIDENCE</p><h2>${esc(a.primaryBrand)} · ${esc(a.name)}</h2><p class="muted">${a.metrics.noteCount} 篇内容 · ${fmt(a.metrics.likes)} 赞</p>${a.noteIds.map(id=>{const n=state.notes.find(n=>n.note_id===id);return `<article><h3>${esc(n.title)}</h3><p>${esc(n.body||'未提供正文')}</p><p>${esc(n.source_account)} · ${fmt(n.likes)} 赞 · 发布 ${esc(n.published_date)}</p><p class="muted">点赞截点 ${esc(n.likes_captured_at)}</p><p>复核说明：${esc(n.reason||'已核对分类和动作归并')}</p>${n.url?`<a href="${esc(n.url)}" target="_blank" rel="noopener noreferrer">查看来源 ↗</a>`:'<small class="muted">该示例无真实帖子链接。</small>'}</article>`;}).join('')}`;$('#detail').showModal();}
async function analyzeWithDeepSeek(){if(!state.report)return;const input=$('#deepseek-key'),apiKey=String(input?.value||sessionStorage.getItem(DEEPSEEK_KEY)||'').trim();if(!apiKey)return toast('请先填写 DeepSeek API Key。');sessionStorage.setItem(DEEPSEEK_KEY,apiKey);const button=$('[data-ai-analyze]');button.disabled=true;button.textContent='分析中…';try{const notes=approved().map(n=>({title:n.title,brand:n.brand,action:n.action,modules:n.modules,peripherals:n.peripherals,likes:Number(n.likes)||0,published_date:n.published_date,source_account:n.source_account,review_reason:n.reason})),report={summary:state.report.summary,brandActions:state.report.brandActions};const response=await fetch('/api/ai/analyze',{method:'POST',headers:{'Content-Type':'application/json','X-DeepSeek-Key':apiKey},body:JSON.stringify({report,notes})});const data=await response.json().catch(()=>({}));if(!response.ok)throw Error(data.error||'DeepSeek 分析失败');state.aiInsight=data.analysis;state.log.push(`${new Date().toLocaleTimeString()} · DeepSeek 生成报告辅助分析`);saveSnapshot();render();toast('DeepSeek 分析已生成。');}finally{if(button.isConnected){button.disabled=false;button.textContent='生成 AI 分析';}}}
async function download(type){if(!state.report)return;if(type==='docx'){const response=await fetch('/api/report.docx',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({report:state.report,notes:approved(),aiInsight:state.aiInsight,log:state.log})});if(!response.ok){const data=await response.json().catch(()=>({}));throw Error(data.error||'Word 报告生成失败');}const blob=await response.blob();const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='signal-report.docx';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('Word 报告已下载。');return;}const content=type==='json'?JSON.stringify({...state.report,reviewHistory:state.log},null,2):'\uFEFF'+Papa.unparse(makeExportRows(state.notes),{escapeFormulae:true});const url=URL.createObjectURL(new Blob([content],{type:type==='json'?'application/json;charset=utf-8':'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=`signal-demo.${type}`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('已导出本次复核结果。');}
document.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b)return;try{if(b.dataset.page)go(b.dataset.page);if(b.dataset.go)go(b.dataset.go);if(b.dataset.reviewFilter){state.reviewFilter=b.dataset.reviewFilter;saveSnapshot();render();return;}if(b.dataset.folderAction==='create')createFolder($('#folder-date')?.value,$('#folder-name')?.value);if(b.dataset.folderAction==='rename')renameFolder($('#folder-rename')?.value);if(b.hasAttribute('data-run'))run();if(b.hasAttribute('data-bulk-confirm'))confirmAll();if(b.hasAttribute('data-select')){state.selected=Number(b.dataset.select);saveSnapshot();render();}if(b.hasAttribute('data-toggle-lock'))toggleLock();if(b.hasAttribute('data-exclude'))saveReview(true);if(b.hasAttribute('data-publish'))await publish();if(b.hasAttribute('data-ai-analyze'))await analyzeWithDeepSeek();if(b.dataset.detail)detail(b.dataset.detail);if(b.dataset.export)download(b.dataset.export);if(b.id==='reset'&&confirm('重置会清空本次复核记录，恢复示例。继续吗？')){clearSnapshot();await loadCSV(await(await fetch('/sample.csv?v=50')).text(),'sample.csv');go('overview');}}catch(error){toast(error.message);}});
document.addEventListener('submit',e=>{if(e.target.id==='review-form'){e.preventDefault();saveReview();}});
document.addEventListener('change',async e=>{if(e.target.id==='upload'){const f=e.target.files[0];if(!f)return;try{if(f.size>10*1024*1024)throw Error('请使用小于 10 MB 的 CSV。');if(state.suggested&&!confirm('导入将替换当前内容和复核记录，继续吗？'))return;await loadCSV(await f.text(),f.name);render();toast('导入成功。点击生成建议开始分析。');}catch(error){state.error=error.message;render();}}if(e.target.id==='module-filter'){state.filter=e.target.value;render();}if(e.target.id==='folder-dashboard-select'||e.target.id==='folder-review-select'){state.activeFolderId=e.target.value;const first=state.notes.findIndex(n=>inScope(n));if(first>=0)state.selected=first;saveSnapshot();render();}});
document.addEventListener('input',e=>{if(e.target.id==='search'){const pos=e.target.selectionStart;state.search=e.target.value;render();$('#search').focus();$('#search').setSelectionRange(pos,pos);}});
const saved=readSnapshot();const initialCsv=saved?.file&&saved.file!=='sample.csv'?Promise.resolve(saved.csv):fetch('/sample.csv?v=50').then(r=>r.text());initialCsv.then(csv=>loadCSV(csv,saved?.file||'sample.csv')).then(render).catch(e=>{$('#main').innerHTML=`<div class="error">载入失败：${esc(e.message)}</div>`;});
}
