const assert=require('node:assert/strict');
const fs=require('node:fs');
const Papa=require('papaparse');
const {suggest,makeExportRows}=require('./app.js');
const {convert}=require('../tools/import-radar.cjs');
const notes=Papa.parse(fs.readFileSync(__dirname+'/sample.csv','utf8'),{header:true,skipEmptyLines:true}).data.map(suggest);
assert.equal(notes.length,10);
assert.equal(notes.filter(n=>n.uncertain).length,2);
assert.equal(notes[9].modules.includes('新品'),false,'Negated 上新 text must not be classified as 新品');
assert.equal(makeExportRows(notes).length,0,'Unreviewed notes must not be exported');
notes.forEach((n,i)=>n.status=i<8?'approved':'excluded');
const result=convert(Papa.unparse(makeExportRows(notes)));
assert.equal(result.notes.length,8);
assert.equal(result.brandActions.length,4);
assert.equal(result.summary.likes,9870);
assert.equal(result.summary.moduleSummary['联名'].likes,2800);
notes[1].action='拆分动作';
assert.equal(convert(Papa.unparse(makeExportRows(notes))).brandActions.length,5);
assert.throws(()=>convert(Papa.unparse([...makeExportRows(notes),makeExportRows(notes)[0]])),/重复笔记/);
console.log('PASS: uncertain evidence, review gate, exclusion, grouping/split, multi-label counts and duplicate validation.');
