window.SignalCollector=({state,$,esc,heading,suggest,saveSnapshot,go,toast,createFolder,renameFolder})=>{
const collector={lastSequence:0,timer:null,message:'等待扩展同步数据。'};
const sample={note_id:'demo-capture-001',url:'https://www.xiaohongshu.com/explore/demo-capture-001',title:'桂花乌龙秋日新品体验',body:'虚构演示样本：新品桂花乌龙上市，随套餐赠送限定玩偶。',brand:'待识别品牌',source_account:'演示观察员',source_type:'小红书',published_date:'2026-09-20',metrics:{likes:{raw:'1,286',value:1286},collects:{raw:'236',value:236},comments:{raw:'48',value:48}},likes_captured_at:new Date().toISOString(),tags:['#新品','#桂花乌龙'],content_type:'图文'};
function normalize(input){const n=input?.note||input;if(!n||typeof n!=='object')throw Error('没有找到笔记数据');const id=String(n.note_id||'').trim(),title=String(n.title||'').trim();if(!id||!title)throw Error('采集数据缺少 note_id 或 title');const likes=n.metrics?.likes?.value??n.likes;return {...n,note_id:id,title,brand:String(n.brand||'待识别品牌'),body:String(n.body||''),source_account:String(n.source_account||''),source_type:'小红书',published_date:String(n.published_date||''),likes_captured_at:n.likes_captured_at||new Date().toISOString(),tags:Array.isArray(n.tags)?n.tags:[],metrics:n.metrics||{likes:{raw:String(likes??''),value:Number(likes)||0},collects:{},comments:{}},content_type:n.content_type||'图文'};}
function currentFolder(){return(state.weekFolders||[]).find(f=>f.id===state.activeFolderId);}
function weekFor(value){const d=new Date((value||new Date().toISOString().slice(0,10))+'T00:00:00'),day=d.getDay()||7;d.setDate(d.getDate()-day+1);const start=d.toISOString().slice(0,10),endDate=new Date(d);endDate.setDate(d.getDate()+6);const end=endDate.toISOString().slice(0,10);return{id:'week-'+start,label:start.replaceAll('-','.')+' – '+end.replaceAll('-','.'),start,end};}
function folders(){return(state.weekFolders||[]).map(f=>'<option value="'+esc(f.id)+'" '+(f.id===state.activeFolderId?'selected':'')+'>'+esc(f.label)+'</option>').join('');}
function folderDirectory(){const all=state.weekFolders||[],size=5,total=Math.max(1,Math.ceil(all.length/size));state.folderPage=Math.min(Math.max(Number(state.folderPage)||0,0),total-1);const rows=all.slice(state.folderPage*size,(state.folderPage+1)*size),folder=currentFolder();return '<section class="panel folder-directory"><div class="panel-heading"><div><p class="eyebrow">COLLECTION INDEX</p><h2>已创建的集合</h2></div><span class="muted">'+all.length+' 个</span></div><div class="folder-table-wrap"><table><thead><tr><th>集合</th><th>笔记</th><th>状态</th></tr></thead><tbody>'+(rows.length?rows.map(f=>{const count=state.notes.filter(n=>n.week_id===f.id).length;return '<tr class="'+(f.id===state.activeFolderId?'is-active':'')+'"><td><strong>'+esc(f.label)+'</strong><small>'+esc(f.start&&f.end?f.start+' – '+f.end:'模拟集合')+'</small></td><td>'+count+' 篇</td><td>'+(f.id===state.activeFolderId?'<span class="tag green">当前</span>':'<span class="muted">可切换</span>')+'</td></tr>';}).join(''):'<tr><td colspan="3" class="muted">还没有集合，先在上方创建。</td></tr>')+'</tbody></table></div><div class="folder-directory-tools"><label>重命名当前集合<input id="capture-folder-rename" value="'+esc(folder?.label||'')+'" placeholder="先选择集合"></label><button class="secondary" type="button" data-capture="rename-folder" '+(folder&&folder.id!=='sample-data'?'':'disabled')+'>保存名称</button></div><div class="folder-pagination"><button class="text-button" type="button" data-folder-page="prev" '+(state.folderPage?'':'disabled')+'>← 上一页</button><span class="muted">'+(state.folderPage+1)+' / '+total+'</span><button class="text-button" type="button" data-folder-page="next" '+(state.folderPage<total-1?'':'disabled')+'>下一页 →</button></div></section>';}
function item(n){return '<article class="inbox-item"><div><strong>'+esc(n.title)+'</strong><p>'+esc(n.brand||'待识别品牌')+' · '+esc(n.source_account||'未知作者')+' · '+esc(n.published_date||'日期待复核')+'</p><small>点赞 '+esc(n.metrics?.likes?.raw||n.metrics?.likes?.value||'未读取')+' · 评论 '+esc(n.metrics?.comments?.raw||n.metrics?.comments?.value||'未读取')+'</small></div><button class="text-button danger" type="button" data-remove-capture="'+esc(n.note_id)+'">删除</button></article>';}
function collection(){const inbox=state.captureInbox||[],folder=currentFolder(),sampleOnly=folder?.id==='sample-data';let html=heading('SIGNAL / INBOX','先收集，再复核。','数据采集只负责收件箱清理；字段审核统一在内容复核完成。','<button class="secondary" data-capture="create-folder">创建本周集合</button>');html+='<div class="collector-layout"><section class="browser-shell connector"><div class="connector-head"><span class="connection-dot"></span><div><p class="eyebrow">CAPTURE INBOX</p><h2>'+inbox.length+' 条待处理笔记</h2><p class="muted">'+(sampleOnly?'模拟数据集合只读，请先创建业务集合。':folder?'当前集合：'+esc(folder.label):'先创建一个集合，再把收件箱送入内容复核。')+'</p></div><span class="tag green">扩展已连接</span></div>';html+='<div class="folder-bar"><label>当前集合<select id="folder-select"><option value="">请选择集合</option>'+folders()+'</select></label><label>集合名称<input id="capture-folder-name" placeholder="可选，自定义名称"></label><button class="secondary" type="button" data-capture="create-folder">创建集合</button></div>';html+='<div class="inbox-list">'+(inbox.length?inbox.map(item).join(''):'<div class="capture-empty"><span>↙</span><p>扩展同步后的笔记会先出现在这里。</p></div>')+'</div>';html+='<div class="collector-actions"><button class="secondary" type="button" data-capture="sample">载入演示样本</button><button class="primary" type="button" data-capture="move-to-review" '+(!inbox.length||!folder||sampleOnly?'disabled':'')+'>移入内容复核 →</button></div>';html+='<details><summary>粘贴采集 JSON</summary><form id="capture-json"><textarea name="payload" rows="5" placeholder="{&quot;note_id&quot;:&quot;...&quot;,&quot;title&quot;:&quot;...&quot;}" required></textarea><button class="secondary">加入收件箱</button></form></details><p id="browser-status" role="status">'+esc(collector.message)+'</p></section>';html+='<aside class="panel capture-panel"><p class="eyebrow">WORKFLOW</p><h2>数据采集只做三件事</h2><ol class="inbox-rules"><li>接收扩展缓存的笔记</li><li>删除不想要的内容</li><li>按集合送入内容复核</li></ol><p class="muted">标题、品牌、日期和互动数据会自动带入；人工判断集中在复核台。</p>'+folderDirectory()+'</aside></div>';return html;}
function renderCollector(){if(state.page!=='collection')return;$('#main').innerHTML=collection();mountCollector();}
function receiveMany(inputs,message){const map=new Map((state.captureInbox||[]).map(n=>[n.note_id,n]));for(const input of inputs){const n=normalize(input);map.set(n.note_id,{...map.get(n.note_id),...n});}state.captureInbox=[...map.values()];collector.message=message||'已收到扩展同步的笔记。';saveSnapshot();renderCollector();}
async function moveToReview(){const folder=currentFolder(),inbox=state.captureInbox||[];if(!folder)return toast('请先创建或选择一个集合。');if(folder.id==='sample-data')return toast('模拟数据集合只用于演示，请先创建或选择业务集合。');if(!inbox.length)return toast('收件箱为空。');const existing=new Set(state.notes.map(n=>n.note_id)),fresh=inbox.filter(n=>!existing.has(n.note_id));if(!fresh.length)return toast('这些笔记已经在内容复核中。');const rows=fresh.map(n=>({...n,brand:n.brand||'待识别品牌',published_date:n.published_date||new Date().toISOString().slice(0,10),likes:String(n.metrics?.likes?.value??n.likes??0),week_id:folder.id,week_label:folder.label,peripherals:''}));const response=await fetch('/api/report',{method:'POST',body:Papa.unparse(rows.map((row,i)=>({...row,action_id:'capture-'+i,action_name:row.title,modules:'新品'})))}),data=await response.json();if(!response.ok)throw Error(data.error);state.notes.push(...(state.suggested?rows.map(suggest):rows.map(row=>({...row,status:'pending',history:[],modules:[],reason:'',locked:false}))));state.captureInbox=inbox.filter(n=>!fresh.some(row=>row.note_id===n.note_id));state.activeFolderId=folder.id;state.sourceCsv=Papa.unparse(state.notes.map(n=>({note_id:n.note_id,brand:n.brand,title:n.title,body:n.body||'',published_date:n.published_date,likes:n.likes,likes_captured_at:n.likes_captured_at,source_account:n.source_account,source_type:n.source_type,url:n.url||'',week_id:n.week_id||'',week_label:n.week_label||''})));state.file=folder.label+' 采集样本.csv';state.selected=Math.max(state.notes.length-fresh.length,0);state.report=null;state.log.push(new Date().toLocaleTimeString()+' · '+folder.label+' 收件箱移入 '+fresh.length+' 篇内容复核');saveSnapshot();go('review');toast('已移入 '+folder.label+'，共 '+fresh.length+' 篇。');}
async function pollCapture(){if(state.page!=='collection')return;try{const data=await fetch('/api/capture/pending?after='+collector.lastSequence).then(r=>r.json());if(data.sequence>collector.lastSequence){collector.lastSequence=data.sequence;receiveMany(data.captures||[]);}}catch{}finally{if(state.page==='collection')collector.timer=setTimeout(pollCapture,1800);}}
function mountCollector(){clearTimeout(collector.timer);pollCapture();}
document.addEventListener('click',async e=>{const b=e.target.closest('[data-capture], [data-remove-capture], [data-folder-page]');if(!b)return;try{if(b.dataset.folderPage){const total=Math.max(1,Math.ceil((state.weekFolders||[]).length/5));state.folderPage=Math.min(Math.max(state.folderPage+(b.dataset.folderPage==='next'?1:-1),0),total-1);saveSnapshot();renderCollector();return;}if(b.dataset.removeCapture){state.captureInbox=(state.captureInbox||[]).filter(n=>n.note_id!==b.dataset.removeCapture);saveSnapshot();renderCollector();toast('已从收件箱删除。');return;}if(b.dataset.capture==='rename-folder'){if(renameFolder)renameFolder($('#capture-folder-rename')?.value);return;}if(b.dataset.capture==='sample')receiveMany([sample],'已载入虚构演示样本。');if(b.dataset.capture==='create-folder'){if(createFolder)createFolder('', $('#capture-folder-name')?.value);else{const folder=weekFor(new Date().toISOString().slice(0,10));state.weekFolders=[...(state.weekFolders||[]).filter(f=>f.id!==folder.id),folder];state.activeFolderId=folder.id;saveSnapshot();renderCollector();toast('已创建 '+folder.label+' 集合。');}}if(b.dataset.capture==='move-to-review')await moveToReview();}catch(error){toast(error.message);}});
document.addEventListener('change',e=>{if(e.target.id==='folder-select'){state.activeFolderId=e.target.value;saveSnapshot();renderCollector();}});
document.addEventListener('submit',e=>{if(e.target.id!=='capture-json')return;e.preventDefault();try{receiveMany([JSON.parse(new FormData(e.target).get('payload'))],'JSON 已加入收件箱。');e.target.reset();}catch(error){collector.message=error.message;const status=$('#browser-status');if(status)status.textContent=error.message;toast(error.message);}});
return {collection,mountCollector};
};
